server: 
   servlet.context-path: /shieldSecurity
   port: 8082
   max-http-header-size: 2MB
   tomcat.max-http-form-post-size: 50MB
   
spring:
  application:
      name: shieldSecurity
  servlet: 
      multipart: 
         max-file-size: 100MB
         max-request-size: 100MB
  jackson:
     date-format: yyyy-MM-dd HH:mm:ss
     time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shield_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    initialSize: 30  #配置初始化大小/最小/最大
    minIdle: 30
    maxActive: 50
    maxWait: 100000   #获取连接等待超时时间
    timeBetweenEvictionRunsMillis: 100000    #间隔多久进行一次检测，检测需要关闭的空闲连接
    minEvictableIdleTimeMillis: 300000      #一个连接在池中最小生存的时间
  data:   
    mongodb: 
#       uri: mongodb://dunan:123456@154.211.103.182:27017/dunan?authMechanism=SCRAM-SHA-256
       host: 127.0.0.1
       port: 27017
       database: shield_security
       username: root
       password: root
    
# Redis数据库索引（默认为0）
  redis: 
     database: 0
     timeout: 5000  #连接超时时间（毫秒）
     host: 127.0.0.1  #Redis服务器地址
     port: 6379  #Redis服务器连接端口
     jedis: 
        pool: 
           max-active: 8  #连接池最大连接数（使用负值表示没有限制）
           max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
           max-idle: 8   #连接池中的最大空闲连接
           min-idle: 0   #连接池中的最小空闲连接

#远程接口调用地址
http_url: http://192.168.1.12:5007/


filePath: D://user
DEFAULT_PASSWORD: qwer123456



#coingecko  API sign
coingecko-sign: CG-zDQmuNUZ7uwuzUMAhMykcW6g

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
